export function allOrigins(url: string) {
    return `https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`;
}

export function randomNumber(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

export const mainConfigURL = 'https://ntp.msn.com/resolver/api/resolve/v3/config/?expType=AppConfig&expInstance=default&apptype=edgeChromium&v=20220314.291&targetScope={"audienceMode":"adult","browser":{"browserType":"edgeChromium","version":"100","ismobile":"false"},"deviceFormFactor":"desktop","domain":"ntp.msn.com","locale":{"content":{"language":"pt","market":"br"},"display":{"language":"pt","market":"br"}},"os":"windows","platform":"web","pageType":"ntp","pageExperiments":["prg-1s-p2pre","prg-1sw-accu10c","prg-1sw-cfi2c","prg-1sw-dsbl-prerend","prg-1sw-ep-g","prg-1sw-gevte","prg-1sw-grevtt","prg-1sw-hdukr","prg-1sw-l2icon","prg-1sw-nen3di","prg-1sw-newsbkt","prg-1sw-newsprec","prg-1sw-newspreviewc","prg-1sw-newsskipc","prg-1sw-oly-rev-cf","prg-1sw-spdiscarscf","prg-1sw-splog","prg-1sw-swsvg","prg-1sw-swsvg2","prg-1sw-swsvg3","prg-1sw-swsvg4","prg-adspeek","prg-esxboxt","prg-fin-cqlx","prg-fin-gm","prg-hp-grablue","prg-hp-tsc","prg-ias","prg-ndualauth","prg-nodualauth","prg-nofcsvtcc","prg-prn-admix4","prg-prong2-aa","prg-ssprime-c","prg-upsaip-w-t","prg-wea-nortate","prg-wpo-ifp-c","prg-wpo-sovfuz-c","prg-wtch-prev-t","prg-wtchrr1"]}';
export const weatherURL = 'https://assets.msn.com/service/weather/overview?apikey=UhJ4G66OjyLbn9mXARgajXLiLw6V75sHnfpU60aJBB&ocid=weather-peregrine&market=BR&scn=APP_ANON&units=C&wrapodata=false&includemapsmetadata=true&cuthour=true&filterRule=card&includenowcasting=true&nowcastingapi=2&distanceinkm=10&regionDataCount=20&orderby=distance&days=5&pageOcid=anaheim-ntp-peregrine&source=undefined_csr&hours=13&inclup=1&region=br&locale=pt-br&lat=-28.482999801635742&lon=-48.784000396728516&xuxa=123';