import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import '@testing-library/jest-dom';
import FolderContainer from './FolderContainer';
import { FolderDataType, WebsiteDataType } from '../../entities';

// Mock getIconURL as its implementation is not relevant to this component's tests
jest.mock('../../utils', () => ({
  getIconURL: jest.fn((url: string) => `mock-icon-url-for-${url}`),
}));

const mockFolderDataEmpty: FolderDataType = {
  id: 'folder-1',
  title: 'Empty Folder',
  children: [],
  type: 'folder',
};

const mockChildSite1: WebsiteDataType = {
  id: 'site-1',
  title: 'Site 1',
  url: 'http://site1.com',
  type: 'website',
  icon: 'icon1.png',
};
const mockChildSite2: WebsiteDataType = {
  id: 'site-2',
  title: 'Site 2',
  url: 'http://site2.com',
  type: 'website',
};
const mockChildSite3: WebsiteDataType = {
  id: 'site-3',
  title: 'Site 3',
  url: 'http://site3.com',
  type: 'website',
};
const mockChildSite4: WebsiteDataType = {
  id: 'site-4',
  title: 'Site 4',
  url: 'http://site4.com',
  type: 'website',
};
const mockChildSite5: WebsiteDataType = {
  id: 'site-5',
  title: 'Site 5',
  url: 'http://site5.com',
  type: 'website',
};

const mockFolderDataWithChildren: FolderDataType = {
  id: 'folder-2',
  title: 'Fun Sites',
  children: [
    mockChildSite1,
    mockChildSite2,
    mockChildSite3,
    mockChildSite4,
    mockChildSite5,
  ],
  type: 'folder',
};

describe('FolderContainer', () => {
  const mockOnOpenFolder = jest.fn();
  const mockOnRenameFolder = jest.fn();
  const mockOnRemoveFolder = jest.fn();

  beforeEach(() => {
    // Reset mocks before each test
    mockOnOpenFolder.mockClear();
    mockOnRenameFolder.mockClear();
    mockOnRemoveFolder.mockClear();
    (require('../../utils').getIconURL as jest.Mock).mockClear();
  });

  describe('Rendering', () => {
    it('renders the folder title', () => {
      render(
        <FolderContainer
          id="test-folder"
          folderData={mockFolderDataWithChildren}
          onOpenFolder={mockOnOpenFolder}
          onRenameFolder={mockOnRenameFolder}
          onRemoveFolder={mockOnRemoveFolder}
        />,
      );
      expect(screen.getByText('Fun Sites')).toBeInTheDocument();
    });

    it('renders up to 4 child icons when children are present', () => {
      render(
        <FolderContainer
          id="test-folder"
          folderData={mockFolderDataWithChildren}
          onOpenFolder={mockOnOpenFolder}
          onRenameFolder={mockOnRenameFolder}
          onRemoveFolder={mockOnRemoveFolder}
        />,
      );
      const images = screen.getAllByRole('img');
      expect(images).toHaveLength(4); // Expecting 4 images for the children icons

      // Check src for explicitly provided icon
      expect(images[0]).toHaveAttribute('src', 'icon1.png');
      expect(images[0]).toHaveAttribute('alt', 'Site 1');

      // Check src for icon generated by getIconURL
      expect(images[1]).toHaveAttribute(
        'src',
        'mock-icon-url-for-http://site2.com',
      );
      expect(images[1]).toHaveAttribute('alt', 'Site 2');
    });

    it('renders a generic empty folder icon when no children are present', () => {
      const { container } = render(
        <FolderContainer
          id="test-folder"
          folderData={mockFolderDataEmpty}
          onOpenFolder={mockOnOpenFolder}
          onRenameFolder={mockOnRenameFolder}
          onRemoveFolder={mockOnRemoveFolder}
        />,
      );

      expect(screen.getByText('Empty Folder')).toBeInTheDocument();

      // Check for the FaFolder icon by looking for an SVG element
      const svgElement = container.querySelector('svg');
      expect(svgElement).toBeInTheDocument();

      // Ensure no child site images are rendered
      expect(screen.queryAllByRole('img')).toHaveLength(0);
    });
  });

  describe('Callbacks and Interactions', () => {
    it('calls onOpenFolder when the container is clicked', () => {
      render(
        <FolderContainer
          id="test-folder"
          folderData={mockFolderDataWithChildren}
          onOpenFolder={mockOnOpenFolder}
          onRenameFolder={mockOnRenameFolder}
          onRemoveFolder={mockOnRemoveFolder}
        />,
      );
      fireEvent.click(screen.getByText('Fun Sites'));
      expect(mockOnOpenFolder).toHaveBeenCalledTimes(1);
    });

    it('calls onRenameFolder when "Rename" menu item is clicked', () => {
      render(
        <FolderContainer
          id="test-folder"
          folderData={mockFolderDataWithChildren}
          onOpenFolder={mockOnOpenFolder}
          onRenameFolder={mockOnRenameFolder}
          onRemoveFolder={mockOnRemoveFolder}
        />,
      );

      const menuButton = screen.getByRole('button', { name: 'Options' });
      fireEvent.click(menuButton);

      const renameMenuItem = screen.getByText('Rename');
      fireEvent.click(renameMenuItem);

      expect(mockOnRenameFolder).toHaveBeenCalledTimes(1);
      expect(mockOnOpenFolder).not.toHaveBeenCalled();
    });

    it('calls onRemoveFolder when "Remove" menu item is clicked', () => {
      render(
        <FolderContainer
          id="test-folder"
          folderData={mockFolderDataWithChildren}
          onOpenFolder={mockOnOpenFolder}
          onRenameFolder={mockOnRenameFolder}
          onRemoveFolder={mockOnRemoveFolder}
        />,
      );

      const menuButton = screen.getByRole('button', { name: 'Options' });
      fireEvent.click(menuButton);

      const removeMenuItem = screen.getByText('Remove');
      fireEvent.click(removeMenuItem);

      expect(mockOnRemoveFolder).toHaveBeenCalledTimes(1);
      expect(mockOnOpenFolder).not.toHaveBeenCalled();
    });
  });
});
